version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    image: server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app/server
      # - node_modules:/usr/app/server/node_modules
    networks:
      - server-network
    command: ./wait-for.sh db:27017 -- /usr/app/server/node_modules/.bin/nodemon server/js
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - server-network
    ports:
      - "27018:27017"

networks:
  server-network:
    driver: bridge

volumes:
  dbdata:
  # node_modules:
